### PR TITLE
Hex

### PR DESCRIPTION
**Pull request by brandoneprice31**
Created `EncodeHex` and `DecodeHex` functions for converting a hexadecimal string to a hashid and then back.

### CODE REVIEW

**Comment by brandoneprice31** [comment]
@speps ping

**Comment by brandoneprice31** [comment]
@speps ping

**Comment by speps** [comment]
Thanks a lot for your contribution! However, I'm questioning the usefulness of it? It seems like it's more helper functions than anything else and could stay in your own code base given that it's just a few lines of trivial code. I'm not opposed to including it but I want to know what's the use case, have more unit test coverage (what's the expected string, with or without 0x, etc.), and documentation.

**Comment by brandoneprice31** [comment]
Hi @speps thank you for getting back.  As you can see here, other hash id libraries have similar functions for converting a hex string to a hash id and back:
- [ruby](https://github.com/peterhellberg/hashids.rb/blob/master/lib/hashids.rb#L36)
- [python](https://github.com/peterhellberg/hashids.rb/blob/master/lib/hashids.rb#L36)

I'm sure other libraries have implement these too.. I just haven't looked elsewhere.

The most popular use case is for converting between a mongo bson id to a hash id.  I'm using the `encode_hex` function in my ruby services, and so I need a similar function in my go services in order to `decode_hex`.  I'm sure there are others out there that are running into the same sort of problem.

**Comment by brandoneprice31** [comment]
anyways, if you think this is worth merging, I'll happily create more unit tests first... just let me know

**Comment by brandoneprice31** [comment]
hi @speps just wanted to check in.  would you like me to write unit tests for this?

**Comment by speps** [comment]
Yes please, but most importantly documentation. See how the others are documented, you need to specify how the methods expect arguments to be formatted.

**Comment by dolmen** [comment]
Besides that, the encoding is really awkward: `"0123456789abcdef"` is encoded as `[]int{16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31}` before being passed to `Encode`. This is pure insanity. And this encoding is absolutely not documented (not even a reference to the python or ruby original implementation from which @brandoneprice31 suggests this crack comes from).

**Comment by speps** [comment]
I wouldn't mind giving ownership to someone else @dolmen to be honest. I do agree it should be less bloated, I'll see what I could do for 2.0 but if you have some time, I wouldn't mind a cleanup PR to get us to 2.0.

**Comment by dolmen** [comment]
`DecodeHex` also doesn't properly check that decoded numbers are correctly in range [16, 31].

**Pull request merged**
